# DB settings
DB_USERNAME = "admin"
DB_PASSWORD = "admin"
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "extyl_test_task_db"

# Data processing settings
SLEEP_TIME_SECONDS = 3
LIST_DATA_COUNT = 150000
PROCESSING_BATCH_SIZE = 5000
UPDATE_RECORDS_BATCH_SIZE = 500
CREATE_RECORDS_BATCH_SIZE = 500
